### ISSUE TITLE
Have the map fill the full height of container

### ISSUE THREAD

**Issue by davve14** [phegman/vue-mapbox-gl#61]
Is it possible to fill the full height of the container?
height: 100% doesnt seemt to work.

**Comment by gorbypark** [comment]
Are you setting 100% height on the `map` id?
```css
#map {
  height:100%;
}
```
